In [17]:
import numpy as np

# Define the Hamiltonian and the initial condition
hbar = 1 # Planck constant
w0 = 1 # between ground to excited state Energy difference
w1 = 1 # between ground to excited state Frequency difference
sz = np.array ([[1, 0], [0, -1]]) # Pauli matrix for z
sx = np.array ([[0, 1], [1, 0]]) # Pauli matrix for x
H = -hbar/2 * (w0 * sz + w1 * sx) # Hamiltonian
rho0 = np.eye (2) / 2 # Initial density matrix, np.eye는 대각선 성분이 1인 행렬

# Define a function to solve the Liouville-von Neumann equation
def solve_LvN (H, rho0, t):
    # H: Hamiltonian matrix
    # rho0: Initial density matrix
    # t: Time array
    # return: Density matrix array
    
    # Calculate the commutator of H and rho0
    comm = -1j/hbar * (H @ rho0 - rho0 @ H)
    
    # Calculate the density matrix at each time step using Euler's method
    rho = np.zeros ((len (t), 2, 2), dtype= complex) # Initialize the density matrix array
    rho [0] = rho0 # Set the initial condition
    dt = t [1] - t [0] # Time step
    for i in range (1, len (t)):
        rho [i] = rho [i-1] + dt * comm # Update the density matrix using Euler's method
    
    return rho

# Define a time array
t = np.linspace (0, 10, 100)

# Solve the Liouville-von Neumann equation
rho = solve_LvN (H, rho0, t)

# Print the density matrix at the final time step
print (rho [-1])


[[0.5+0.j 0. +0.j]
 [0. +0.j 0.5+0.j]]


In [3]:
np.eye(2)/2

array([[0.5, 0. ],
       [0. , 0.5]])

In [5]:
np.zeros((len(t),2,2),dtype=complex)

array([[[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j],
  

In [6]:
comm = -1j/hbar * (H @ rho0 - rho0 @ H)
    
    # Calculate the density matrix at each time step using Euler's method
rho = np.zeros ((len (t), 2, 2), dtype= complex) # Initialize the density matrix array
rho [0] = rho0 # Set the initial condition
dt = t [1] - t [0] # Time step
for i in range (1, len (t)):
    rho [i] = rho [i-1] + dt * comm # Update the density matrix using Euler's method

In [7]:
print(comm)

[[0.-0.j 0.-0.j]
 [0.-0.j 0.-0.j]]


In [8]:
rho[0]

array([[0.5+0.j, 0. +0.j],
       [0. +0.j, 0.5+0.j]])

In [12]:
dt=t[1]-t[0]
print(dt)

0.10101010101010101


In [16]:
for i in range (1, len (t)):
    rho [i] = rho [i-1] + dt * comm # Update the density matrix using Euler's method

SyntaxError: 'return' outside function (264999879.py, line 4)

In [20]:
import numpy as np

# Define the Hamiltonian and the initial condition
hbar = 1 # Planck constant
w0 = 1 # Energy difference
w1 = 1 # Frequency difference
sz = np.array ([[1, 0], [0, -1]]) # Pauli matrix for z
sx = np.array ([[0, 1], [1, 0]]) # Pauli matrix for x
H = -hbar/2 * (w0 * sz + w1 * sx) # Hamiltonian
rho0 = np.eye (2) / 2 # Initial density matrix

# Define the interaction operators and the decay rates
gamma = 0.1 # Decay rate
n = 1 # Occupation number
sm = np.array ([[0, 0], [1, 0]]) # Lowering operator
sp = np.array ([[0, 1], [0, 0]]) # Raising operator
Vk = np.sqrt (gamma * (1 + n)) * sm + np.sqrt (gamma * n) * sp # Interaction operator

# Define a function to solve the Liouville-von Neumann equation with decoherence term
def solve_LvN_deco (H, Vk, rho0, t):
    # H: Hamiltonian matrix
    # Vk: Interaction matrix
    # rho0: Initial density matrix
    # t: Time array
    # return: Density matrix array
    
    # Calculate the commutator of H and rho0
    comm_H = -1j/hbar * (H @ rho0 - rho0 @ H)
    
    # Calculate the commutator of Vk and rho0
    comm_Vk = -0.5 * (Vk @ rho0 @ Vk - Vk @ Vk @ rho0 - rho0 @ Vk @ Vk + Vk @ rho0 @ Vk)
    
    # Calculate the density matrix at each time step using Euler's method
    rho = np.zeros ((len (t), 2, 2), dtype= complex) # Initialize the density matrix array
    rho [0] = rho0 # Set the initial condition
    dt = t [1] - t [0] # Time step
    for i in range (1, len (t)):
        rho [i] = rho [i-1] + dt * (comm_H + comm_Vk) # Update the density matrix using Euler's method
    
    return rho

# Define a time array
t = np.linspace (0, 10, 100)

# Solve the Liouville-von Neumann equation with decoherence term
rho_deco = solve_LvN_deco (H, Vk, rho0, t)

# Print the density matrix at the final time step
print (rho_deco [-1])


[[0.5+0.j 0. +0.j]
 [0. +0.j 0.5+0.j]]


In [28]:
import numpy as np
import scipy.integrate

In [29]:
hbar = 1 # 감소된 플랑크 상수
H = np.array ([[1, 0.5], [0.5, 2]]) # 해밀토니안 행렬
rho0 = np.array ([[0.8, 0.2], [0.2, 0.2]]) # 초기 밀도 행렬
t0 = 0 # 초기 시간
tf = 10 # 최종 시간
n = 100 # 시간의 구간 개수

In [30]:
def f(t, rho):
    rho = rho.reshape (2, 2) # 밀도 행렬을 2 x 2 형태로 변환
    comm = -1j/hbar * (H @ rho - rho @ H) # 커뮤테이터를 계산
    return comm.ravel () # 커뮤테이터를 1차원 배열로 변환

In [31]:
t = np.linspace (t0, tf, n) # 시간의 배열을 생성
sol = scipy.integrate.solve_ivp (f, (t0, tf), rho0.ravel (), t_eval=t) # 방정식을 품
rho = sol.y.reshape (n, 2, 2) # 밀도 행렬을 n x 2 x 2 형태로 변환