In [79]:
import numpy as np

# Define the coefficients for the initial state
c_1 = 1
c_2 = 0
c_3 = 0

# Define the frequencies corresponding to each energy level
w_1 = 1.0  # this will depend on the specific energy level
w_2 = 2.0
w_3 = 3.0

# Define the time
t = 2.0  # you can change this to simulate the state at different times

# Construct the initial state
psi_0 = np.array([c1, c2, c3])

# Calculate the state at time t
psi_t = np.array([np.exp(-1j * w1 * t) * psi_0[0], 
                  np.exp(-1j * w2 * t) * psi_0[1], 
                  np.exp(-1j * w3 * t) * psi_0[2]])

print("State at time t (psi_t):")
print(psi_t)


State at time t (psi_t):
[-0.41614684-0.90929743j -0.        +0.j          0.        +0.j        ]


In [80]:
# Define Planck's constant/2pi
h = 1.0
hbar = h / (2 * np.pi) # np.pi는 3.141592653589793

# Define the energies for the three levels
E1 = hbar * w_1
E2 = hbar * w_2
E3 = hbar * w_3

# Construct the unperturbed Hamiltonian matrix
H_0 = np.diag([E1, E2, E3])

print("Unperturbed Hamiltonian:")
print(H_0)

# For the perturbed Hamiltonian, we need the dipole moment and the electric field
# H_i = -d * E, d = -e * r, d = transition dipole moment

Rabi_frequency_p = 1
Rabi_frequency_c = 1
phi_p = 1 # laser phase
phi_c = 1
w_p = 1
w_c = 1

H_i = np.array([[0, 0, 0],
                [(hbar/2) * Rabi_frequency_p * np.exp(-1j * phi_p) * np.exp(-1j * w_p * t), 0, 0],
                [0,(hbar/2) * Rabi_frequency_c * np.exp(-1j * phi_c) * np.exp(-1j * w_c * t),0]])

print("\nPerturbed Hamiltonian:")
print(H_i)

# The total Hamiltonian is the sum of the unperturbed and perturbed Hamiltonians
H = H_0 + H_i

print("\nTotal Hamiltonian:")
print(H)

Unperturbed Hamiltonian:
[[0.15915494 0.         0.        ]
 [0.         0.31830989 0.        ]
 [0.         0.         0.47746483]]

Perturbed Hamiltonian:
[[ 0.       +0.j          0.       +0.j          0.       +0.j        ]
 [-0.0787811-0.01122997j  0.       +0.j          0.       +0.j        ]
 [ 0.       +0.j         -0.0787811-0.01122997j  0.       +0.j        ]]

Total Hamiltonian:
[[ 0.15915494+0.j          0.        +0.j          0.        +0.j        ]
 [-0.0787811 -0.01122997j  0.31830989+0.j          0.        +0.j        ]
 [ 0.        +0.j         -0.0787811 -0.01122997j  0.47746483+0.j        ]]


In [81]:
# state간 frequency?
w_21 = w_2 - w_1
w_32 = w_3 - w_2
w_31 = w_3 - w_1

# decay
# R_i는 i state에서 spontaneous decay하는 frequency?
R_1 = 1
R_2 = 1
R_3 = 1
r= np.array([[0, (R_1 + R_2)/2, (R_1 + R_3)/2],
                 [(R_2 + R_1)/2, 0, (R_2 + R_3)/2],
                 [(R_3 + R_1)/2, (R_3 + R_2)/2, 0]])

print("\nDecay rate:")
print(r)


Decay rate:
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]


In [82]:
detuning_1 = w_p - w_21
detuning_2 = w_c - w_32
g_21 = 1
E_p = 1

p_21 = (-1j * g_21 * E_p * np.exp(-1j * w_p * t))/(((r[1][0])-1j * detuning_1)+((Rabi_frequency_c)**2/4)/(r[2][0] - 1j * (detuning_1+detuning_2)))

print("\ndensity matrix 2행 1열 성분")
print(p_21)


density matrix 2행 1열 성분
(-0.7274379414605454+0.3329174692377139j)


In [83]:
g_32 = 1
E_c = 1

p_31 = (-1j * g_32 * E_c * np.exp(-1j * w_c * t) * np.exp(-1j * phi_c * t) * p_21)/(r[2][0] - 1j * (detuning_1+detuning_2))

print("\ndensity matrix 3행 1열 성분")
print(p_31)


density matrix 3행 1열 성분
(-0.7681362293202929-0.2235323985591407j)


In [84]:
# Doppler broadening이 없을 때 susceptibility
# w_p에 의한 susceptibility
epsilon_0 = 1

Kai = ((4 * 1j * hbar * (g_21**2))/epsilon_0) / ((r[1][0] - 1j * detuning_1) + ((Rabi_frequency_c)**2/4)/(r[2][0] - 1j*(detuning_1+detuning_2)))

print("\n도플러 넓힘이 없을 때 susceptibility")
print(Kai)


도플러 넓힘이 없을 때 susceptibility
0.5092958178940651j
